# User intent for the simulation across different domains
user_intents:
  airline:
    booking_and_reservations:
      - search_flights
      - make_booking
      - modify_booking
      - cancel_booking_request_refund
    checkin_and_boarding:
      - online_checkin
      - seat_selection_or_upgrade
      - boarding_pass_retrieval
    flight_status_and_operations:
      - check_flight_status
      - track_baggage
      - rebook_due_to_disruption
    loyalty_and_services:
      - manage_frequent_flyer_account
      - redeem_or_earn_miles
      - request_lounge_access

  telco:
    account_and_billing:
      - view_or_pay_bill
      - dispute_charges
      - setup_autopay
    plans_and_services:
      - upgrade_or_downgrade_plan
      - add_ons_data_roaming_family_lines
      - prepaid_recharge
    technical_support:
      - report_network_outage
      - troubleshoot_device_or_sim
      - request_technician_visit
    device_and_sales:
      - buy_or_upgrade_device
      - tradein_or_financing
      - insurance_claims

  health_coach:
    onboarding_and_assessment:
      - create_health_profile
      - set_fitness_goals
      - nutrition_preferences_or_restrictions
    daily_guidance:
      - exercise_recommendations
      - nutrition_tracking_and_meals
      - habit_tracking
    monitoring_and_feedback:
      - log_progress
      - progress_reports
      - personalized_motivation_reminders
    support:
      - ask_health_questions
      - request_plan_adjustments
      - integration_with_wearables

  hotel:
    booking_and_reservations:
      - search_and_book_room
      - modify_reservation
      - cancel_booking
    checkin_and_stay_management:
      - early_checkin_or_late_checkout
      - room_upgrades_or_amenities_request
      - service_requests_housekeeping_laundry_maintenance
    concierge_and_local_services:
      - book_dining_or_spa
      - request_local_recommendations
      - arrange_transportation
    loyalty_and_billing:
      - redeem_loyalty_points
      - request_invoice
      - report_billing_discrepancies

  retail:
    product_discovery_and_purchase:
      - search_products
      - add_to_cart_and_checkout
      - apply_promo_codes
    order_and_delivery:
      - track_order_status
      - modify_or_cancel_order
      - return_or_exchange_items
    account_and_loyalty:
      - manage_account_details
      - apply_or_redeem_rewards
      - subscription_management
    customer_support:
      - report_damaged_or_missing_items
      - warranty_or_repair_requests
      - general_inquiries
